// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gwxwuplmjzlwnqvutkla.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd3eHd1cGxtanpsd25xdnV0a2xhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwOTQ2MTcsImV4cCI6MjA3MDY3MDYxN30.DCPQ4lbKSEkvD-_ANkCKAU1K9YEDb_9DGCsWHFLfVWE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});